# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Populate service facts
  service_facts:

- name: Configure sysctl rules
  ansible.builtin.include_role:
    name: common_physical_machine
    tasks_from: sysctl.yml

- name: Configure common setup
  ansible.builtin.include_role:
    name: common_physical_machine
    tasks_from: common_setup.yml

- name: Configure Pacemaker Seapath resources
  when: "'cluster_machines' in group_names"
  block:

    - name: Copy Pacemaker Seapath Resource-Agent files
      ansible.posix.synchronize:
        src: pacemaker_ra/
        dest: /usr/lib/ocf/resource.d/seapath/
        rsync_opts:
          - "--chmod=F755"
          - "--chown=root:root"

    - name: Copy VirtualDomain from heartbeat to seapath
      copy:
        remote_src: yes
        src: /usr/lib/ocf/resource.d/heartbeat/VirtualDomain
        dest: /usr/lib/ocf/resource.d/seapath/VirtualDomain
        owner: root
        group: root
        mode: '0755'
        force: yes

    - name: Apply patch to VirtualDomain
      ansible.posix.patch:
        src: VirtualDomain_patch
        dest: /usr/lib/ocf/resource.d/seapath/VirtualDomain
        strip: 0

    - name: Copy ethmonitor from heartbeat to seapath
      copy:
        remote_src: yes
        src: /usr/lib/ocf/resource.d/heartbeat/ethmonitor
        dest: /usr/lib/ocf/resource.d/seapath/ethmonitor
        owner: root
        group: root
        mode: '0755'
        force: yes

    - name: Apply patch1 to ethmonitor
      ansible.posix.patch:
        src: ethmonitor_patch1
        dest: /usr/lib/ocf/resource.d/seapath/ethmonitor
        strip: 0

    - name: Apply patch2 to ethmonitor
      ansible.posix.patch:
        src: ethmonitor_patch2
        dest: /usr/lib/ocf/resource.d/seapath/ethmonitor
        strip: 0

- name: Configure chrony-wait
  ansible.builtin.include_role:
    name: common_physical_machine
    tasks_from: chrony_wait.yml

- name: Configure pacemaker service
  ansible.builtin.include_role:
    name: common_physical_machine
    tasks_from: pacemaker.yml
  vars:
    common_physical_machine_check_service_exists: "{{ services['pacemaker.service'] is defined }}"

- name: Add extra modules to the kernel
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: "^{{ item }}$"
    line: "{{ item }}"
  with_items: "{{ extra_kernel_modules | default([]) }}"

- name: Add br_netfilter to /etc/modules
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: '^br_netfilter$'
    line: 'br_netfilter'
- name: Add raid6_pq to /etc/modules
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: '^raid6_pq$'
    line: 'raid6_pq'

- name: Configure logstash
  ansible.builtin.include_role:
    name: common_physical_machine
    tasks_from: logstash.yml

- name: Configure libvirt
  ansible.builtin.include_role:
    name: common_physical_machine
    tasks_from: libvirt.yml

- name: "Add initramfs-tools scripts: script file (LVM rebooter and log handling)"
  ansible.builtin.copy:
    src: initramfs-tools/scripts/
    dest: /etc/initramfs-tools/scripts/
    mode: '0755'
  notify: Rebuild initramfs if necessary

- name: Get the /var/log/ device
  command: "findmnt -n -o SOURCE --target /var/log"
  register: debian_physical_machine_varlog_dev
  changed_when: false

- name: Set fact /var/log/ device
  set_fact:
    debian_physical_machine_lvm_rebooter_log_device: "{{ debian_physical_machine_varlog_dev.stdout }}"

- name: Get the /var/log/ relative path
  shell: "realpath --relative-to=$(findmnt -n -o TARGET --target /var/log/) /var/log"
  register: debian_physical_machine_varlog_path
  changed_when: false

- name: Set fact /var/log/ relative path
  set_fact:
    debian_physical_machine_lvm_rebooter_log_path: "{{ debian_physical_machine_varlog_path.stdout }}"

- name: Copy rebooter.conf # noqa: risky-file-permissions
  template:
    src: initramfs-tools/conf.d/rebooter.conf.j2
    dest: /etc/initramfs-tools/conf.d/rebooter.conf

- name: Configure initramfs-tools to use busybox
  lineinfile:
    dest: /etc/initramfs-tools/initramfs.conf
    regexp: "^#?BUSYBOX="
    line: "BUSYBOX=y"
    state: present
  notify: Rebuild initramfs if necessary

- name: Add udev rules for lvm2 limitation
  ansible.builtin.copy:
    src: 69-lvm.rules
    dest: /etc/udev/rules.d/69-lvm.rules
    mode: '0644'
  when: ansible_distribution == 'Debian' and ansible_distribution_version | int >= 12

- name: Add rbd type to lvm.conf
  ansible.builtin.lineinfile:
    path: /etc/lvm/lvm.conf
    insertafter: 'devices {'
    line: "        types = [ \"rbd\", 1024 ]"
    state: present

- name: Configure ovs-vswitchd
  ansible.builtin.include_role:
    name: common_physical_machine
    tasks_from: ovs_vswitchd.yml
