# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Customize /etc/environment
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  vars:
    env_list:
      HISTSIZE: 2000000
      HISTFILESIZE: 2000000
      LIBVIRT_DEFAULT_URI: "qemu:///system"
      HISTTIMEFORMAT: '"%F %T "'
      EDITOR: 'vim'
      SYSTEMD_EDITOR: 'vim'
  with_items: "{{ env_list | dict2items }}"
